check:
  - thoth-precommit
  - thoth-build


build:
    build-stratergy: Source
    build-source-script: "image:///opt/app-root/builder"
    base-image: quay.io/thoth-station/s2i-custom-notebook:v0.4.7
    custom-tag: latest
    registry: quay.io
    registry-org: aicoe
    registry-project: time-series
    registry-secret: aicoe-pusher-secret
